FROM registry.access.redhat.com/ubi9/ubi-minimal:9.3

# install packages
RUN microdnf install -y gettext jq tar diffutils gzip

# install binaries
ENV BIN_DIR=/usr/local/bin
ARG TMP_FILE=/tmp/archive.tar.gz
ARG CURL_OPTS='--location --silent'
ARG TAR_OPTS="-zvx --no-same-owner -C $BIN_DIR -f $TMP_FILE"

# install helm
ARG HELM_URL=https://mirror.openshift.com/pub/openshift-v4/clients/helm/latest/helm-linux-amd64.tar.gz
RUN curl $CURL_OPTS "$HELM_URL" -o "$TMP_FILE"
RUN tar --transform='s/-.*//g' $TAR_OPTS helm-linux-amd64

# install oc clients
ARG OC_URL=https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/latest/openshift-client-linux.tar.gz
RUN curl $CURL_OPTS "$OC_URL" -o "$TMP_FILE"
RUN tar $TAR_OPTS oc
RUN ln -s "$BIN_DIR/oc" "$BIN_DIR/kubectl"

# install yq
ARG YQ_URL=https://github.com/mikefarah/yq/releases/download/v4.42.1/yq_linux_amd64.tar.gz
RUN curl $CURL_OPTS "$YQ_URL" -o "$TMP_FILE"
RUN tar $TAR_OPTS --transform='s/_.*//g' ./yq_linux_amd64

# install tkn
ARG TKN_URL=https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/pipelines/latest/tkn-linux-amd64.tar.gz
RUN curl $CURL_OPTS "$TKN_URL" -o "$TMP_FILE"
RUN tar $TAR_OPTS opc tkn tkn-pac

# install argo cli
ARG ARGOCD_URL=https://github.com/argoproj/argo-cd/releases/download/v2.9.2/argocd-linux-amd64
RUN curl $CURL_OPTS "$TKN_URL" -o "$BIN_DIR/argocd"

# fix permissions on binaries
RUN chmod 755 "$BIN_DIR"/*

# cleanup image
RUN microdnf clean all && rm -rf "$TMP_FILE"

